name: card_markethome
description: "A new mini app market home version 2.0 of the vdone project"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localization: ^0.2.0

  # image
  flutter_svg: ^2.0.9
  cached_network_image: ^3.2.3

  # localization
  intl: any

  # router
  fluro: ^2.0.5

  #state management
  flutter_bloc: ^8.1.1

  # dio
  dio: ^5.8.0+1
  colorize: ^3.0.0
  equatable: ^2.0.5
  formz: ^0.7.0

  # custom UI
  mobile_scanner: ^5.1.1
  flutter_staggered_grid_view: ^0.7.0
  dropdown_button2: ^2.3.9
  flutter_widget_from_html: ^0.14.8
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  bot_toast: ^4.1.3
  top_snackbar_flutter: ^3.1.0

  # animations
  lottie: ^2.7.0
  flutter_inappwebview: ^6.0.0
  image_gallery_saver: ^2.0.3
  screenshot: ^2.5.0
  permission_handler: ^11.3.1

  device_info_plus: ^9.1.1
  internet_connection_checker_plus: 2.2.0
  socket_io_client: ^2.0.3+1
  universal_platform: ^1.0.0+1

  qr_code_dart_scan: ^0.7.3
  image_picker: ^1.0.7
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/generated/
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      style: snake-case
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: lib/assets/fonts/Inter/Inter-Regular.otf
        - asset: lib/assets/fonts/Inter/Inter-Medium.otf
          weight: 500
        - asset: lib/assets/fonts/Inter/Inter-SemiBold.otf
        - asset: lib/assets/fonts/Inter/Inter-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/Inter/Inter-ExtraBold.otf
        - asset: lib/assets/fonts/Inter/Inter-Italic.otf
          style: italic
